### ISSUE TITLE
Performance of Fibers

### ISSUE THREAD

**Issue by ioquatix** [socketry/async#14]
@tarcieri has raised the good point that Fibers might be expensive. At the very least, we should investigate the memory overhead and performance cost of using Fibers vs another approach.

If it's hard to do a comparison, perhaps we could simply provide benchmarks - number of connections per second/memory usage.

**Comment by tarcieri** [comment]
If you care about JRuby at all (which perhaps you don't), Fibers are going to be substantially more expensive as they're each backed by native threads.

**Comment by ioquatix** [comment]
What would be more efficient on JRuby?

**Comment by tarcieri** [comment]
Callbacks/promises

**Comment by christopheraue** [comment]
I'm developing a library very (very) similar to socketry/async right now and also came across the expensive creation of fibers. I work around it by reusing created fibers at the cost of creating a proc instead.

The basic idea is to create a fiber with an infinite loop running inside it. It is started with a proc to run given as argument. After each iteration of said loop the fiber is put back into a pool and yields back to where it was resumed. Later it is taken out of the pool again and resumed with another proc to run. And so on.

I haven't benchmarked my library directly yet, but for another lib built on top of it (additionally doing asynchronous IO through a pipe and some bookkeeping stuff) I get around 150k executions inside a fiber per second for CRuby. I haven't tested how JRuby behaves.

Maybe this is a path for you. You can look at the code implementing it here: https://github.com/christopheraue/m-ruby-concurrently/blob/master/mrblib/proc_fiber.rb

**Comment by tarcieri** [comment]
Having done something quite similar in Celluloid, this is a recipe for resource leaks. Anything that that uses thread local variables is actually setting them on a fiber. This leads to these variables being set, sometimes lazily (thanks ActiveRecord) then after a fiber is swapped, a similar resource being reinitialized and stored as a thread local. These values persist in the fiber pool, even if there is no need for the resource to persist.

I would strongly recommend against pooling fibers for this reason. Newer versions of Celluloid moved away from a thread pool for this reason, which strategically prevented such resource leaks.

**Comment by tarcieri** [comment]
Regarding better options for the JVM, Reactive Streams are the new (as of Java 8) way to do asynchronous I/O:

http://www.reactive-streams.org/

**Comment by christopheraue** [comment]
Can't the problem with thread vars be handled by manually copying them from fiber to fiber on each switch? And probably clearing them when a fiber is returned to the pool? After all, they are intended to be thread local anyway and the code setting them does not seem to take fibers into account. Otherwise, it would have noticed that the thread vars are indeed fiber local.

**Comment by tarcieri** [comment]
Celluloid has code to try to clean up thread locals. Unfortunately `Thread` provides no API to actually delete thread locals. Your only option is to set them to `nil`.

Even then, there were ongoing problems with this code not always being run and other ongoing bugs. Avoiding pooling completely eliminates this bugclass, and unless you have a silver bullet, my battle-scar-stricken-hard-won-knowledge opinion is pooling should simply be avoided as the performance gains are not worth dealing with the ensuing resource leaks.

**Comment by christopheraue** [comment]
Having nullified entries of thread locals shouldn't be a problem since all fibers will share the exact same variables anyway. So, all of them will be set again the next time the thread locals are set for the fiber.

I experienced the problems you described myself. In my case they were always caused by an incomplete control over the code's flow, but not the reuse of fibers. Things were falling through the cracks that shouldn't. Sure, always using freshly created fibers helps mitigating problems with unclean states. But the only real cure was to patch those cracks and make the control flow "perfect". But for that reason, I agree it's a good idea to make pooling optional. The mentioned issues are too easy to introduce. At least, with a switch there is a safety net.

So, do I understand you correctly, that in your experience fiber pooling won't cause problems if it can be ensured that 1) control flow is perfect and 2) thread locals are dealt with as discussed? Or is there something else that could go wrong?

**Comment by tarcieri** [comment]
If you have absolutely perfect code, you will still experience the thread variable name leak (which is also just generally confusing), but perhaps you won't experience other problems. I can't say for sure.

However, testing that your code is "perfect" is pretty much impossible, leaving it open to regress at any time. We experienced several such regressions over the lifetime of Celluloid. And I'm not sure we ever achieved the mythical "perfect" status.

**Comment by christopheraue** [comment]
Alright, I just wanted to sort out which of what you were saying can be attributed to fiber pools with certainty.

**Comment by ioquatix** [comment]
I implemented a similar stack in C++, culminating in a web server, and got out of 1 core, the same levels of performance that took 8 cores in Ruby. So, Ruby is at least 10x slower than fairly decent C++ code and probably not worse than 100x. I'll provide some more detailed reports.

**Comment by picatz** [comment]
@ioquatix This is going to be a _bit_ off topic, but have you ever heard of [Crystal](https://crystal-lang.org/)?

I really look forward to your report! 👍

**Comment by ioquatix** [comment]
Yes, I've been following Crystal. I assume you want to know what I think of it?

I like the idea. I experimented with something similar many years ago (as most programmers do I guess): https://github.com/ioquatix/kai

Language design is very complex.

Crystal's whole program type inference, is trying to do something that is probably impossible in general: either actually unsolvable or practically infeasible due to the high computational complexity. I think it's a great idea. The trade off of compiling vs interpreting is an interesting one - the cost to compile a function might be high so it only makes sense to do that if you know it will be executed at least a few hundred times.

If you look at high performance dynamic languages/environments, e.g. lua, jvm, most modern JavaScript interpreters, they basically try to figure out what things should be compiled or not, and the specific type signatures of the arguments, local variables and return types, so that they can be lowered to efficient assembly instructions. When the function is invoked, they perform quick type check/unbox, execute the compiled code, and then return to the interpreter (often via a "trampoline").

The nature (benefit?) of this approach is that the user is able to use a dynamically typed language without worrying about the efficiently of the implementation.

Crystal tries to expose this a bit more, but my understanding is that general type inference typically involve combinatorial explosions. Apparently even Swift has this problem in some cases.

The problem with any layer of abstraction is that the trade-offs are often non-obvious. I think that's ultimately why C is still popular, and C++ too: they have a zero-cost abstraction model - if you don't use it you don't pay for it in performance.

I could go on, it's a very interesting discussion, it's probably more interesting to have a face 2 face discussion over a beer.

**Comment by picatz** [comment]
I'd love for you to go on. I like yo' stuff.

## Go Similarities
I've found Crystal to be something like if Go and Ruby had a baby.

## Community
One thing that's really caught my interest is the community involvement, especially on places like Gitter where most projects are usually much, much quieter. It's also fairly easy to get started building applications and libraries with a few minor hiccups that are probably natural when picking up a new language -- regardless of similar it is to Ruby. You can also generally find some helpful advice / guidance on Gitter with people willing to offer their time.

## Types
Crystal's type system is both fairly simple and complex at the same time. It's only bitten me in the butt once thus far which made it really annoying to debug an issue and required a lil bit of messing about to get it to work. Specially, an un-expected union type didn't allow a method; and I didn't know it was being compiled as a union type. There's ways to explicitly work with these things, but, it's generally really easy to ignore them almost entirely.

## REPL
I think what's almost a shame about Crystal is how hard it is to achieve a REPL in the language. I happen to love Ruby's IRB ( and PRY is much better ). I've also yet to find any sort of debugging option that isn't just `puts`'n all over the place.

I really wish I had a nice PRY-like tool for Crystal. It makes my Ruby development so much more enjoyable.

#### Beer
You're right though, maybe this conversation would be best over a beer 🍻 face to face. But, ya' know.

#### It's Fun
If you haven't programmed something serious-ish in Crystal, I'd really recommend it! I think you'd find it interesting; and mostly because I'd love to see you to build libraries in Crystal and [ join the community](https://gitter.im/crystal-lang/crystal) eventually 🤗 

Obviously, only if you want to. 😉 And, of course time is a thing ⌛️ and people generally lack that.

##### Why I Use Crystal
I'm mostly using Crystal right now because I wanted Go style concurrency patterns and (needed) speed, but with Ruby style syntax. And, _damn_, does it deliver.

**Comment by ioquatix** [comment]
> You're right though, maybe this conversation would be best over a beer 🍻 face to face. But, ya' know.

We can try doing this over Google Hangouts lol

**Comment by picatz** [comment]
You's right. The internet is cray' like that. 

But, definitely!

**Comment by ioquatix** [comment]
I've made a PR to MRI to improve the performance of fiber yield/resume: https://bugs.ruby-lang.org/issues/14739

The next step once this is accepted is to make a PR to improve the reuse of fiber stacks.
