### ISSUE TITLE
Async 2.0 requires Ruby version 3.1

### ISSUE THREAD

**Issue by yassenb** [socketry/async#141]
There should be no reason to require `>= 3.1.0` instead of `>= 3.0.3`. The change was introduced with https://github.com/socketry/async/commit/d16f7fad5859dfd8f731388ce98eea2b42f55501 which doesn't really make sense since `io-event` itself requires only `>= 3.0`

**Comment by ioquatix** [comment]
Yes you are correct and I haven't had a chance to address this yet.

**Comment by ioquatix** [comment]
Coming back to this, there are some bugs in 3.0 which are fixed in 3.1, which make Async unstable in 3.0 which is why I set the minimum version to 3.1 - and there are some autoload bugs (which you can work around in 3.1) which are fixed in 3.2 - this would be the first release which should be production ready IMHO.
