### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by woto** [socketry/async#15]
Hi, while trying to run examples getting this results

```
root@a42ebebf32a8:/app/async/examples# ruby ./aio.rb 
Creating server
/usr/local/bundle/gems/async-0.13.0/lib/async/reactor.rb:87:in `wrap': undefined method `[]' for IO:Class (NoMethodError)
	from /usr/local/bundle/gems/async-0.13.0/lib/async/task.rb:69:in `block in initialize'
	from /usr/local/bundle/gems/async-0.13.0/lib/async/task.rb:69:in `collect'
	from /usr/local/bundle/gems/async-0.13.0/lib/async/task.rb:69:in `initialize'
	from /usr/local/bundle/gems/async-0.13.0/lib/async/reactor.rb:98:in `new'
	from /usr/local/bundle/gems/async-0.13.0/lib/async/reactor.rb:98:in `async'
	from ./aio.rb:17:in `<main>'
```

```
root@a42ebebf32a8:/app/async/examples# ruby ./echo.rb 
D, [2017-05-01T20:05:41.933171 #263] DEBUG -- : [#<Async::Reactor:0x00558802e0bca0> Ensure] Exiting run-loop (stopped: false exception: undefined method `connect' for Async::TCPServer:Class)...
D, [2017-05-01T20:05:41.933868 #263] DEBUG -- : [["#<Async::Task:0x00558802e0b930>[failed]", false]]
./echo.rb:25:in `block in echo_client': undefined method `connect' for Async::TCPServer:Class (NoMethodError)
	from /usr/local/bundle/gems/async-0.13.0/lib/async/task.rb:83:in `block in initialize'
```

```
root@a42ebebf32a8:/app/async/examples# ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
```

**Comment by rfestag** [comment]
Same issue here. I'm interested in playing with this gem for an http2 based server. In my case, I'm running Ruby 2.3

**Comment by ioquatix** [comment]
Okay, I'll check what's going on. Sorry about this.

**Comment by ioquatix** [comment]
The examples are fixed. I'm sorry, some of the internals were changing and the examples were not kept up to date. I'm going to take some time this week to review where we are w.r.t. a 1.0 rc. If you are doing some development with async (which is awesome BTW) I'd love to hear your feedback and ideas. In particular, pain points for learning now to use async - what things did you find confusing or hard at first (conceptually, programmatically, etc). I can improve documentation for new users by understanding how you get on.

**Comment by rfestag** [comment]
No worries, thanks for taking a look. FYI, the echo example doesn't work with the latest released version of the gem, but does work with the latest master. The AIO example does appear to work with both.

I was originally looking to implement an HTTP2 server, and was looking for alternatives to Celluloid (since it offers more than I really need...I'm just interested in the async IO and avoiding creating a thread for every connection). I ended up falling back on the HTTP2 support being added to Reel, but am still interested in playing with this to see if I can get a lighter weight server working. I'll definitely let you know if I find anything else, or if the project comes to anything.


I started looking at async to avoid the complexities of Celluloid (I was only really interested in achieving asynchronous IO without threads, not necessarily for all Celluloid offers

**Comment by ioquatix** [comment]
Yes, I'll fix all these issues today.

I'm almost certain that in it's current state, Celluloid will never reach v1.0 - which I think is a problem.

Async is like all the good bits of celluloid, minus the actors. I've been thinking I'll implement something like `async-actor` in the future since I like the concept and it's fun to play with. My core interest though is pervasive asynchronous IO.

**Comment by ioquatix** [comment]
So, I've left Async on the back burner for a few weeks while I let my subconscious digest the current API design. Something wasn't sitting right - the way `Reactor#async(*ios)` takes IOs, wraps them and passes them to the task just didn't feel quite right.

I prefer explicit resource management, e.g. `Socket.accept(server_address) do |peer|` where in all cases the server will be closed. e.g. don't make it the responsibility of the caller to clean up.

I've made a small internal change that has far reaching consequences to the design upstream - no longer `async` takes sockets and wraps them. You must do this explicitly. It forces you to be more aware of the design choices and I think ultimately simplifies how things work.

In terms of how this affects you - I've also decided that sockets don't belong in `async`. The core `async` - once it's done, it should be done. The API is so fundamental, that it shouldn't really be something we expect to change a lot. I don't mind improvements to performance, under the hood, which to some extent are planned (improvements to how timers are handled). But, general changes to the way it works will cause massive upstream disturbances. I also feel like gems with a large surface area never really stabilize and this is detrimental in many ways.

Therefore, there is a new gem which you should depend on, `async-socket`. It will depend on `async` and expose all the socket related functionality you are expecting. It's not done yet but it will be soon. The benefit of this, is that in theory, if someone didn't like the way `async-socket` worked, they could make their own, but the core `async` gem wouldn't change, and is the shared foundation of all this work.

**Comment by rfestag** [comment]
Good to know. I submitted a PR for adding SSL support, but that is probably unnecessary given these changes. Let me know whenever you release async-socket and I'll see if I can get my HTTP2 server working with it instead.

**Comment by ioquatix** [comment]
@rfestag Your PR for SSL support is greatly appreciated and it's definitely something that I want. Shortly, the code for `async-socket` will be up and I think if you can rebase your PR on that it would be awesome.

It's also exactly the reason why it can't go into the `async` gem. The SSLSocket depends on OpenSSL. I think it's simply wrong to have the dependency so deeply seated.

**Comment by tarcieri** [comment]
Have you considered using socketry for this purpose? It has a set of
already-written wrappers, and I would love for there to be a common gem
which is usable for both async I/O and synchronous I/O with thread-safe
timeouts
-- 
Tony Arcieri
