### ISSUE TITLE
[Enhanchment] Make alternate exception reporting (the colorful one) opt in.

### ISSUE THREAD

**Issue by jsaak** [socketry/async#261]
While yours is usable, i prefer the standard ruby one.
Using both is confusing for me.

**Comment by ioquatix** [comment]
Because exceptions do not propagate up to the very top of Ruby, the formatting has to be done by some user-level code.

This is done by the `console` gem here: https://github.com/socketry/console/blob/main/lib/console/event/failure.rb#L46-L72

We could make this a little more flexible but it's not a personal priority of mine.

Alternatively, if you just want to remove the color you can run like this:

![image](https://github.com/socketry/async/assets/30030/31da5f54-ac33-4149-801d-489d5c1c1bbb)

i.e. specify `CONSOLE_OUTPUT=Text` to force non-`XTerm` output.

I'm pretty sure you are after the former, not the latter. In that case, you could write your own output formatter e.g. `CONSOLE_OUTPUT=MyCustomFormatter`. It is just a class that implements `#call(subject, *arguments, **options)` where arguments may be `[exception]` in your case.

**Comment by jsaak** [comment]
If i recreate the original MRI error messages in a function, would you be interested to make that default? :)
Fortunately this is not very important. Closing for now. Maybe if I am not alone with my request they can +1, or something.

**Comment by ioquatix** [comment]
The original MRI formatting is missing important context, e.g. why it failed, etc. I don't think this is worth the effort, but if the integration is minimal then I don't say no. You'd probably need to make a PR to the console gem.
