### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by bryanp** [socketry/async#36]
I'd like to use a custom logger throughout the async library. Currently doing this:

```ruby
Async.instance_variable_set(:@logger, @logger)
```

Can/Should this be supported in a better way?

**Comment by ioquatix** [comment]
Yeah, I'm working on it.

**Comment by ioquatix** [comment]
Do you want to submit a PR to make it an attr_accessor if it's not already?

**Comment by ioquatix** [comment]
Part of what I'm working on is to extract the custom logger out of async: https://github.com/socketry/event

Maybe I'll change it to use built in logger by default, or maybe I'll leave it as event logger. Thoughts?

**Comment by bryanp** [comment]
Sure, will PR the `attr_accessor` change.

Unsure right off on the built in logger vs event logger. I'll keep thinking on it, but can you explain the rationale for logging being a concern of the main async lib at all?

**Comment by ioquatix** [comment]
I don't think logging should be a concern of async directly, but it does need a good buffered logger to be sensical to users.

What I mean is that by default the stdlib logger is unbuffered, and if you have multiple threads/processes using the logger the output gets mixed up and impossible to read.

`Event::Logger` uses a buffer and a single call to write to ensure the output logging is synchronised as much as possible.

**Comment by ioquatix** [comment]
I'm all for small surface area as you probably get that already from the design of async. But logging is a feature for users and it needs to be really good IMHO because it makes a huge difference to knowing what's going on.

I recall having lots of problems with celluloid and the logger, and trying to know the state of a system. That's one of the reasons for the task tree. Ideally we have an interactive `async-pry` type thing where if you press Ctrl-C you can bring up a terminal and debug your task tree / see what things are doing. Falcon already supports some parts of that using USR1. But it's not the best.

**Comment by bryanp** [comment]
Yep, that makes sense. Thanks for explaining your thinking here!

**Comment by bryanp** [comment]
Do you have a preference on where to make the `attr_accessor` change? Looks like it could go either in `async/logger.rb` or in `Advise::Console`.

**Comment by ioquatix** [comment]
There are two options going forward, if you want to make a change right now to the 1.15.x release, I'd be happy with that and I could release it today.

If you want something more future looking, it should go into the new `Event::Console`. Advise is deprecated because someone was willing to give me the gem named `event`.

**Comment by ioquatix** [comment]
You would not believe the number of logging gems that exist on RubyGems, it's unbelievable. Every variant of log, logger, lumberjack, terminal, console, it used in one way or another for some custom logging system.

**Comment by ioquatix** [comment]
I guess I'm not much better :p

**Comment by ioquatix** [comment]
I want to release the event update soon, probably this week. It's just that I want to unify logging across a bunch of different projects to use `Event::Console` and I'm currently wrangling (as discussed above) with an interface that makes sense across all of them.

**Comment by bryanp** [comment]
Cool, I'll just make the change to `Event::Console`. Not a huge rush.

FWIW I recently moved my project over to `log4r` and have been really happy with it so far.

**Comment by ioquatix** [comment]
Can you show me some screenshots of log4r?

Can we also support it in the event logging infrastructure, so that we can do really nice structured log output?

**Comment by ioquatix** [comment]
So, to I've you a bigger perspective on what I'm thinking with `Event` gem - I'm not so interested in just logging text.

What I think is that users are logging structured data, like shell commands, exceptions, object state, etc. To me, there is a native mapping from `object -> console/logger`. But there are other useful mappings, like `object -> msgpack -> network`. I know this is not a new idea, but it seems to me if it's executed well, it serves the basis for, say, aggregating logs between multiple falcon processes, or allowing the user to capture state changes in a system like TracePoint.

**Comment by ioquatix** [comment]
One idea I had was being able to visualise running program state in a web browser by visualising the process/task tree. The way this would be captured is through structured event logging and aggregation. Users could add their own events and then it would be part of the visualisation - e.g.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/30030/54317304-a36d9180-4647-11e9-9bed-a004e6e28f6e.png">

**Comment by ioquatix** [comment]
Here is an example from Python's `asyncio`: https://github.com/aio-libs/aiomonitor

**Comment by bryanp** [comment]
I wrote my own formatters for log4r (which is one of the reasons I chose it; so much easier to format how I wanted than in ruby's logger). Here's what the `human` formatter looks like terminal output:

<img width="841" alt="Screenshot 2019-03-13 14 57 30" src="https://user-images.githubusercontent.com/18920/54317449-6b5f4380-45a0-11e9-98ae-563b03f6da78.png">

(there's also `json` and `msgpack`)

**Comment by ioquatix** [comment]
Love it - so awesome!

So I believe our thinking is in alignment. We both want beautiful human readable errors on the console.

**Comment by ioquatix** [comment]
Just to save me some time, can you point me at the file where you implement your custom formatter?

**Comment by bryanp** [comment]
Yes, very much on the same page here! I haven't pushed the new log4r version, but here it is:

* https://gist.github.com/bryanp/0329d58c753f1fa6e99d970960ad006d

And here's the cli formatter for errors:

* https://github.com/pakyow/pakyow/blob/master/pakyow-core/lib/pakyow/error.rb#L234

**Comment by bryanp** [comment]
Oh, and the cli formatter assumes you're formatting an instance of `Pakyow::Error`.

**Comment by ioquatix** [comment]
Okay, so I'm preparing to release this.

Right now, you can't change `Async.logger`, it's an alias to `Event::Console.logger`. You an set `Event::Console.logger` to whatever you want.

There is one limitation you might run into.

In order to handle buffering, I've extended the way blocks work.

```ruby
Async.logger.info(self) do |buffer|
  buffer.puts "Message"
end
```

This is important to efficiently construct detailed log messages.

I don't know if log4r supports this or not.

**Comment by ioquatix** [comment]
In any case, we can now fix some of these issues in the `Event` gem without affecting Async version, which is one reason for making these two concerns separate.

**Comment by bryanp** [comment]
Excellent. I'll try this out at some point soon.

**Comment by bryanp** [comment]
Confirmed that log4r _does not_ support the block approach you showed above. Does this mean I won't be able to replace `Event::Console.logger` with a log4r instance?

**Comment by ioquatix** [comment]
I might see if I can make a PR to Ruby logger to support buffered I/O. Not much core code uses the buffered style so I dilont think it should cause any problems but maybe.

**Comment by ioquatix** [comment]
Okay, I think we are good with this.

The final implementation addresses your original concern. We also now support scoped loggers per-task (which also apply to all children tasks). It's probably better that you use task-scoped logger rather than replacing the global logger.

The code is now implemented in the [`console`](https://github.com/socketry/console) gem.

**Comment by ioquatix** [comment]
> Confirmed that log4r does not support the block approach you showed above. Does this mean I won't be able to replace Event::Console.logger with a log4r instance?

In a way, we need to find a common denominator for logging that makes the most sense.

I will add documentation to console to show how to do this.

**Comment by ioquatix** [comment]
https://github.com/socketry/console#custom-logger-output
